### ISSUE TITLE
Just to clarify

### ISSUE THREAD

**Issue by SanjulaD** [JAYASHREEPATIL/Project_GECA_ChatBot#4]
can i have email or contact platform from anyone who contributed for this project. i just need some information about this..

**Comment by JAYASHREEPATIL** [comment]
You can contact  jayapatil9830@gmail.com

**Comment by SanjulaD** [comment]
Can you reshare your email with me

**Comment by SanjulaD** [comment]
jayapatil9830@gmail.com is this correct email ? i didnt get this one ***@***.***

**Comment by JAYASHREEPATIL** [comment]
> [jayapatil9830@gmail.com](mailto:jayapatil9830@gmail.com) is this correct email ? i didnt get this one _**@**_.***

Yes this is correct jayapatil9830@gmail.com

**Comment by SanjulaD** [comment]
Okay cool. Actually I did not expect your reply for the issue which I put
in your repository.  I searched your name on linkedin facebook because I
did not find your contact details inside your github account. So I thought
of putting an issue tag for the repository. Thanks for replying. Otherwise
I dont no how to contact you lol!..

Hello *JAYASHREE PATIL,*

*I am Sanjula from Sri Lanka and I am currently a final year
undergraduate at NSBM Green university and also I am an Intern Software
Engineer at Rootcode Labs.*
*First of all I have to thank you for replying to me. Couple of weeks ago I
started my final year so we have a final year project to do as
individuals. *
*Actually I have keen interest in ML , NLP and Conversation AI engines, So
when I went through the docs I found a framework called RASA so I went
through some online courses *
*and got some ground knowledge. So my problem is "*How to ease the
university query solving process by a Conversational AI Agent who can save
time and effort which provides an efficient and accurate answer for any
query based on the dataset of FAQs using Artificial Intelligence, NLP and
Rasa ML framework". So after this problem I went to find solutions and many
docs for my FYP. Then I found your repository which fits 100% of my
problem. In my case I thought of delivering not only a bot and also an
admin panel to visualize all data processes.

So if you have any docs or reports related to your work can you share with
me. I need more case studies on this area..  So it would be great and also
it would be more helpful for me.

Waiting for your kind response.. Till then stay safe🙃
